name: Build

on: [push, pull_request]

jobs:
  build-host:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            artifact-name: Windows x86-64
            architecture: x64
            build-options: ""
          - os: macos-latest
            artifact-name: macOS x86-64
            architecture: x64
            build-options: ""

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}

      - name: Install Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer ${{ matrix.build-options }}
        if: ${{ github.repository_owner != 'wpilibsuite' || !startsWith(github.ref, 'refs/tags/v') }}

      - name: Build with Gradle (Release)
        run: ./gradlew build -PbuildServer -PreleaseMode ${{ matrix.build-options }}
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  build-docker:
    name: "Build - Linux x86-64"
    runs-on: ubuntu-latest
    container: wpilib/ubuntu-base:18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer
        if: ${{ github.repository_owner != 'wpilibsuite' || !startsWith(github.ref, 'refs/tags/v') }}

      - name: Build with Gradle (Release)
        run: ./gradlew build -PbuildServer -PreleaseMode
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v2
        with:
          name: Linux x86-64
          path: build/allOutputs

  combine:
    runs-on: ubuntu-latest
    needs: [build-host, build-docker]
    name: "Combine"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wpilibsuite/build-tools

      - uses: actions/download-artifact@v2
        with:
          path: combiner/products/build/allOutputs

      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/

      - name: Check version number exists
        run: |
          cat combiner/products/build/allOutputs/version.txt
          test -s combiner/products/build/allOutputs/version.txt

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Combine
        if: |
          (!startsWith(github.ref, 'refs/tags/v') &&
          github.ref != 'refs/heads/main') || github.repository_owner != 'wpilibsuite'
        run: cd combiner && ./gradlew publish -Pallwpilib -PbuildName=sysid

      - name: Combine (Main)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/main'
        run: cd combiner && ./gradlew publish -Pallwpilib -PbuildName=sysid
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: "TRUE"
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Combine (Release)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          startsWith(github.ref, 'refs/tags/v')
        run: cd combiner && ./gradlew publish -Pallwpilib -PbuildName=sysid -PreleaseRepoPublish
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: "TRUE"
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: Maven
          path: ~/releases
