name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-host:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            artifact-name: Win64
            architecture: x64
          - os: macos-11
            artifact-name: macOS
            architecture: x64

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set release environment variable
        run: echo "EXTRA_GRADLE_ARGS=-PreleaseMode" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer ${{ env.EXTRA_GRADLE_ARGS }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2023-22.04
            artifact-name: Athena
            build-options: "-Ponlylinuxathena"
          - container: wpilib/raspbian-cross-ubuntu:bullseye-22.04
            artifact-name: Arm32
            build-options: "-Ponlylinuxarm32"
          - container: wpilib/aarch64-cross-ubuntu:bullseye-22.04
            artifact-name: Arm64
            build-options: "-Ponlylinuxarm64"
          - container: wpilib/ubuntu-base:22.04
            artifact-name: Linux
            build-options: "-Ponlylinuxx86-64"
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set release environment variable
        run: echo "EXTRA_GRADLE_ARGS=-PreleaseMode" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/v')

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 13

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer ${{ matrix.build-options }} ${{ env.EXTRA_GRADLE_ARGS }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  combine:
    runs-on: ubuntu-22.04
    needs: [build-host, build-docker]
    name: "Combine"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: wpilibsuite/build-tools

      - uses: actions/download-artifact@v3
        with:
          path: combiner/products/build/allOutputs

      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/

      - name: Check version number exists
        run: |
          cat combiner/products/build/allOutputs/version.txt
          test -s combiner/products/build/allOutputs/version.txt

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Combine
        if: |
          (!startsWith(github.ref, 'refs/tags/v') &&
          github.ref != 'refs/heads/main') || github.repository_owner != 'wpilibsuite'
        run: cd combiner && ./gradlew publish -Pallwpilib -PbuildName=sysid

      - name: Combine (Main)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          github.ref == 'refs/heads/main'
        run: cd combiner && ./gradlew publish -Pallwpilib -PbuildName=sysid
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: "TRUE"
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Combine (Release)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          startsWith(github.ref, 'refs/tags/v')
        run: cd combiner && ./gradlew publish -Pallwpilib -PbuildName=sysid -PreleaseRepoPublish
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: "TRUE"
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: Maven
          path: ~/releases
